apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-fibo-deployment
  labels:
    app: node-fibo
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30%
  selector:
    matchLabels:
      app: node-fibo
  template:
    metadata:
      labels:
        app: node-fibo
    spec:
      priorityClassName: node-priority-class
      imagePullSecrets:
        - name: regcred
      containers:
        - name: node-fibo
          image: 283770677653.dkr.ecr.us-west-1.amazonaws.com/node-fibo-example:v1
          imagePullPolicy: Always
          ports:
            - name: nodejs-port
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: nodejs-port
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: nodejs-port
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
          resources:
            limits:
              cpu: 40m
              memory: 120Mi